version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

commands:
  deploy-command:
    parameters:
      BRANCH:
        type: string
      HEROKU_APP_NAME:
        type: string
    steps:
      - run: heroku config:set YARN_PRODUCTION=false -a <<parameters.HEROKU_APP_NAME>>
      - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/<<parameters.HEROKU_APP_NAME>>.git <<parameters.BRANCH>>:main

jobs:
  build:
    docker:
      - image: node:16
    resource_class: large
    parallelism: 10

    steps:
      - checkout

      - restore_cache:
          name: Restore yarn Package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock"}}

      - run:
          name: Build app
          command: |
            yarn
            yarn build

      - save_cache:
          name: Save yarn Package cache
          key: yarn-packages-{{ checksum "yarn.lock"}}
          paths:
            - node_modules

      - persist_to_workspace:
          paths:
            - "."
          root: ~/project

  test:
    docker:
      - image: node:16
    resource_class: large
    parallelism: 10

    steps:
      - attach_workspace:
          at: ~/project/

      - restore_cache:
          name: Restore yarn Package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock"}}

      - run:
          name: Test app
          command: |
            yarn test

  deploy:
    executor: heroku/default

    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/project/

      - heroku/install

      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - deploy-command:
                HEROKU_APP_NAME: jrivo-joke-app
                BRANCH: master


workflows:
    build:
      jobs:
        - build:
            filters:
                branches:
                  only:
                    - master
        - test:
            requires:
              - build
        - deploy:
            requires:
              - test