version: 2.1
jobs:
  build:
    docker:
      - image: node:16
    resource_class: large
    parallelism: 10

    steps:
      - checkout

      - run:
          name: Install yarn
          command: |
            npm install --global yarn

      - run:
          name: Build app
          command: |
            yarn
            yarn build


      - run:
          name: Test app
          command: |
            yarn test