version: 2.1
jobs:
  build:
    docker:
      - image: node:16
    resource_class: large
    parallelism: 10

    steps:
      - checkout

      - restore_cache:
          name: Restore yarn Package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock"}}

      - run:
          name: Build app
          command: |
            yarn
            yarn build

      - save_cache:
          name: Save yarn Package cache
          key: yarn-packages-{{ checksum "yarn.lock"}}
          paths:
            - node_modules

  test:
    docker:
      - image: node:16
    resource_class: large
    parallelism: 10

    steps:
      - checkout

      - restore_cache:
          name: Restore yarn Package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock"}}

      - run:
          name: Test app
          command: |
            yarn test